# Numpy- numeric python

In [1]:
l1=[1,2,3,4]
l2=[5,6,7,8]
l1+l2

[1, 2, 3, 4, 5, 6, 7, 8]

In [3]:
import numpy as np
arr1=np.array(l1)
arr2=np.array(l2)
arr1+arr2
arr1-arr2
arr1*arr2

array([ 5, 12, 21, 32])

In [4]:
lst=[101,283,987]
arr3=np.array(lst)
print(arr3+10)

[111 293 997]


In [5]:
type(arr3)

numpy.ndarray

## NumPy object creation


## 1 dimensional array

In [9]:
a=np.array([1,2,3,4])
b=np.array([[1,2,3],[4,5,6]])
print(a)
print("----------")
print(b)

[1 2 3 4]
----------
[[1 2 3]
 [4 5 6]]


In [10]:
print("shape of a is ",a.shape)
print("shape of b is ",b.shape)

shape of a is  (4,)
shape of b is  (2, 3)


## dimension

In [14]:
print("dimension of a is ",a.ndim)

dimension of a is  2


## size

In [16]:
print(b.size)

6


# datatype

In [18]:
print(a.dtype)

int32


## Matrix creation

In [23]:
np.array([1,2,4,4,5,6,4,5,6]).reshape(3,3)

array([[1, 2, 4],
       [4, 5, 6],
       [4, 5, 6]])

In [25]:
np.matrix([[1,2,3],[4,5,6],[7,8,9]])

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [30]:
np.eye(2)#identity matrix

array([[1., 0.],
       [0., 1.]])

In [35]:
np.zeros((4,3),dtype=np.int32)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [36]:
np.ones((3,4),dtype=np.int32)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [37]:
np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [38]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

###Practice Exercise:
Store the marks and IDs of three students as NumPy arrays. The marks are [20, 30, 40] and IDs are [0,2,4]. Store array for marks in a variable marks and the one for IDs in another variable ids. Display both marks and ids.

In [41]:
marks=np.array([20,30,40])
IDs=np.array([0,2,4])
print(marks)
print(IDs)

[20 30 40]
[0 2 4]


## indxing and slicing

In [42]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
a[2]

array([7, 8, 9])

In [44]:
a[2][1]

8

In [49]:
print(a[2])

[7 8 9]


## integer array indexing

In [51]:
a=np.array([[1,2],[3,4],[5,6]])

In [53]:
a[[0,1,2],[0,1,0]]

array([1, 4, 5])

In [54]:
a[[0,0],[1,1]]

array([2, 2])

In [55]:
np.array(a[[0,0],[1,1]])

array([2, 2])

In [57]:
a=np.array([[1,2],[3,4],[5,6]])
mask=a>3
print(mask)
print(a[mask])

[[False False]
 [False  True]
 [ True  True]]
[4 5 6]


## vectoristaion

In [60]:
a=np.array([1,2,3,4,5,6,67,8])
a[a>2]

array([ 3,  4,  5,  6, 67,  8])

# Axes Notation

In [67]:
a=np.array([1,2,3],[4,4,5])
a.sum(axis=0)# calculates sum over columns


TypeError: Field elements must be 2- or 3-tuples, got '4'

In [71]:
a.sum(axis=0)#calculates sum over columns

96

In [69]:
a.sum()

96

# We have a buy sell problem:

Initialize an array [[40, 35, 20], [21, 48, 70]] which constitutes the prices on 2 consecutive day at 3 different sessions of the day. The objective is to buy at minimum price on day 1 and sell at maximum on day.

1. Find the minimum price on day 1.
2. Find the maximum price on day 2.
3. Calculate the profit and print it.

In [3]:
import numpy as p
arra=p.array([[40,35,20],[21,48,70]])
arra

array([[40, 35, 20],
       [21, 48, 70]])

# hello

In [16]:
min_price = arra[0].min()
min_price

20

In [17]:
max_price=arra[1].max()
max_price

70

In [18]:
profit=max_price-min_price
profit

50

# broadcasting 

In [4]:
p.arange(4)

array([0, 1, 2, 3])

In [12]:
p.ones((3,3)) +p.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [6]:
p.arange(3)

array([0, 1, 2])

In [14]:
p.arange(6).reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [26]:
p.arange(3).reshape(3,1)+p.arange(3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

### Practice Exercise
In this task, you will normalize i.e. subtract the minimum value and divide by the range:

1. Create a random 5x5 matrix with the help of np.random.random((5,5))
2. Calculate the minimum and maximum value with the help of .min() and .max() methods respectively
3. Now using the power of broadcasting subtract the minimum value from each element and divide by their range (maximum-minimum) to normalize. Save this normalized as z_norm
4. Print the standardized arra

In [17]:
a=p.random.random((5,5))
a

array([[0.88594528, 0.48393082, 0.19364381, 0.14280311, 0.87986356],
       [0.98353407, 0.42676893, 0.34837045, 0.1186176 , 0.52587611],
       [0.37874089, 0.15170472, 0.56674999, 0.37934842, 0.48606146],
       [0.09556615, 0.24701784, 0.86760487, 0.84405608, 0.69099725],
       [0.02848286, 0.43887169, 0.62866928, 0.06143449, 0.87895419]])

In [18]:
x=a.min()
x

0.028482857218153468

In [19]:
y=a.max()
y

0.9835340726963799

In [21]:
z=(a-x)/y
z

array([[0.87181771, 0.46307289, 0.16792601, 0.11623416, 0.86563417],
       [0.97104029, 0.40495402, 0.32524302, 0.09164374, 0.50572041],
       [0.35612191, 0.1252848 , 0.54727858, 0.35673961, 0.4652392 ],
       [0.06820638, 0.22219361, 0.85317026, 0.82922721, 0.67360594],
       [0.        , 0.41725939, 0.6102345 , 0.0335033 , 0.86470957]])

In [22]:
y

0.9835340726963799

# mini project

## Columns=features
## rows = observations


In [25]:
data_file="makeSenseOfCensus.csv"

In [26]:
data=p.genfromtxt(data_file,delimiter=",",skip_header=1)
data

array([[39., 13.,  4., ...,  0., 40.,  0.],
       [50., 13.,  4., ...,  0., 13.,  0.],
       [38.,  9.,  4., ...,  0., 40.,  0.],
       ...,
       [48., 13.,  4., ...,  0., 58.,  1.],
       [40., 10.,  4., ...,  0., 40.,  0.],
       [39., 13.,  4., ...,  0., 50.,  1.]])

In [41]:
data

array([[39., 13.,  4., ...,  0., 40.,  0.],
       [50., 13.,  4., ...,  0., 13.,  0.],
       [38.,  9.,  4., ...,  0., 40.,  0.],
       ...,
       [48., 13.,  4., ...,  0., 58.,  1.],
       [40., 10.,  4., ...,  0., 40.,  0.],
       [39., 13.,  4., ...,  0., 50.,  1.]])

In [29]:
new_record=[[23,45,6,7,89,4,0,9]]
new_data=p.concatenate((data,new_record),axis=0)
new_data

array([[39., 13.,  4., ...,  0., 40.,  0.],
       [50., 13.,  4., ...,  0., 13.,  0.],
       [38.,  9.,  4., ...,  0., 40.,  0.],
       ...,
       [40., 10.,  4., ...,  0., 40.,  0.],
       [39., 13.,  4., ...,  0., 50.,  1.],
       [23., 45.,  6., ...,  4.,  0.,  9.]])

In [30]:
age=new_data[:,0]
age

array([39., 50., 38., ..., 40., 39., 23.])

In [31]:
max_age=age.max()
print("amx age=",max_age)

amx age= 90.0


In [32]:
min_age=age.min()
print("minimum age",min_age)

minimum age 17.0


In [33]:
age_mean=age.mean()
print("average age:",age_mean)

average age: 38.035964035964035


In [53]:
age_std=age.std()
print("standard deviation:",age_std)

standard deviation: 13.344610397761235


In [34]:
race=new_data[:,2]
race_0=race[race==0]
race_1=race[race==1]
race_2=race[race==2]
race_3=race[race==3]

race_4=race[race==4]

In [35]:
len_0=len(race_0)
len_1=len(race_1)
len_2=len(race_2)
len_3=len(race_3)
len_4=len(race_4)
print(len_0,len_1,len_2,len_3,len_4)

10 27 110 6 847


In [37]:
len1=[len_0,len_1,len_2,len_3,len_4]
len_arr=p.array(len1)
print("minimum number of citizens in a race",len_arr.min())

minimum number of citizens in a race 6


In [38]:
minority_race=6

In [39]:
if minority_race==len_0:
    minority_race=0
elif minority_race==len_1:
    minority_race=1
elif minority_race==len_2:
    minority_race=2
elif minority_race==len_3:
    minority_race=3
elif minority_race==len_4:
    minority_race=4
print("minority_race:",minority_race)

minority_race: 3


In [40]:
senior=age[age>60]
senior

array([79., 67., 76., 61., 70., 64., 71., 68., 66., 64., 90., 66., 75.,
       65., 64., 61., 65., 77., 62., 76., 63., 66., 67., 65., 62., 63.,
       80., 67., 63., 72., 62., 74., 67., 72., 69., 65., 65., 71., 70.,
       66., 65., 61., 61., 68., 64., 64., 62., 73., 72., 63., 62., 61.,
       71., 63., 63., 67., 81., 64., 67., 78., 63.])

In [43]:
working_hours=new_data[:,6]
working_sum=p.sum(working_hours[age>60])
print("working sum",working_sum)

working sum 1917.0


In [44]:
senior_len=len(senior)
senior_len

61

In [45]:
avg_working=working_sum/senior_len
print("average working hours:",avg_working)

average working hours: 31.42622950819672


In [47]:
if avg_working<=25:
    print("followed")
else:
    print("not followed")

not followed
